name: Debug build
description: Build BeatSketch for Windows, AppImage and Linux Bundle (debug)
author: Janis Hutz
inputs:
  out:
    description: "The output directory"
    default: ""
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.out }}
branding:
  icon: book
  color: red
