name: Draft a new release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The Tag to create for this release
        type: string
        required: true
jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Build the release
        uses: ./.github/actions/main-build
      - name: List files
        run: ls -la
      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "beatsketch-linux.tar.gz,beatsketch-binary-linux.tar.gz,beatsketch-windows.zip"
          body: ""
          draft: true
          generateReleaseNotes: true
          tag: ${{ inputs.tag }}
