name: Draft a new release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The Tag to create for this release
        type: string
        required: true
jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Build the release
        uses: ./.github/actions/main-build
        with:
          out: /github/workspace
      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "beatsketch-linux.tar.gz,beatsketch-binary-linux.tar.gz,beatsketch-windows.zip"
          body: "# BeatSketch ${{ inputs.tag }}"
          draft: true
          generateReleaseNotes: true
          tag: ${{ inputs.tag }}
